package com.example.helb_mobile1.managers;

import android.app.AlarmManager;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.content.Context;
import android.content.Intent;
import android.os.Build;
import android.util.Log;

import java.time.ZoneId;
import java.time.ZonedDateTime;



public class AppNotificationManager {
    /*
    manager for the app's notifications
     */
    public static final String CHANNEL_ID = "inPlaineSightNotifications";
    public static final String EXTRA_NOTIFICATION_TYPE = "notification_type";
    public static final String NOTIF_TYPE_DAILY_WORD = "DailyWord";
    public static final String NOTIF_TYPE_DAILY_RESULTS = "ResultTime";
    public static final int REQUEST_CODE_WORD = 1;
    public static final int REQUEST_CODE_RESULTS = 2;

    private final Context context;

    public AppNotificationManager(Context context) {
        this.context = context.getApplicationContext();
        createNotificationChannel();
    }

    private void createNotificationChannel() {
        //Creates a channel for notifications, so that when the user mutes the app's notifications, it mutes their specified category
        //in this case, we put all our notifications in one channel

        CharSequence name = "In Plaine Sight daily notifications";
        String description = "Reminds the user about the daily word and results of their marker submission";
        //Code generated by ChatGPT
        int importance = NotificationManager.IMPORTANCE_DEFAULT;
        NotificationChannel channel = new NotificationChannel(CHANNEL_ID, name, importance);
        channel.setDescription(description);

        NotificationManager notificationManager = context.getSystemService(NotificationManager.class);
        notificationManager.createNotificationChannel(channel);
    }

    public void scheduleReminder(String type, int hour, int requestCode) {
        //schedules a notification
        //type so that the NotificationReceiver knows what to do with the notification
        //hour for obvious purposes
        //requestCode so Android OS knows if duplicate Notification or not
        //Code mostly generated by ChatGPT, modified

        Intent intent = new Intent(context, NotificationReceiver.class);
        intent.putExtra(EXTRA_NOTIFICATION_TYPE, type);

        PendingIntent pendingIntent = PendingIntent.getBroadcast(
                context,
                requestCode,
                intent,
                PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE
        );

        ZoneId belgium = ZoneId.of(TimeConfig.SERVER_TIMEZONE);
        ZonedDateTime now = ZonedDateTime.now(belgium);
        ZonedDateTime target = now.withHour(hour).withMinute(0).withSecond(0).withNano(0);

        //if target date is already behind current time, schedule the notification for next day
        if (target.isBefore(now)) {
            target = target.plusDays(1);
        }
        Log.d("AppNotificationManager", "Scheduling " + type + " notification at " + target.toString());

        AlarmManager alarmManager = (AlarmManager) context.getSystemService(Context.ALARM_SERVICE);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) { //need to handle permission for exact alarms (only for API 31+)
            if (alarmManager.canScheduleExactAlarms()) {
                alarmManager.setExactAndAllowWhileIdle(
                        AlarmManager.RTC_WAKEUP,
                        target.toInstant().toEpochMilli(),
                        pendingIntent
                );
            } else {
                Log.d("AppNotificationManager", "permission denied");
            }
        }else { //API 30
            alarmManager.setExactAndAllowWhileIdle(
                    AlarmManager.RTC_WAKEUP,
                    target.toInstant().toEpochMilli(),
                    pendingIntent
            );
        }

    }

}

